config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resource :session, only: [:new, :create, :destroy]
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  get 'signout' => 'sessions#destroy'

  resources :users do
    resources :medications
  end

  resources :posts

  post 'signup'  => 'users#create'
  get 'profile' => 'medications#index'
  get 'forum' => 'posts#index'

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  before_save :get_pill_fill_info

  has_many :user_medications
  has_many :users, through: :user_medications
  has_many :post_medications
  has_many :posts, through: :post_medications

  def get_pill_fill_info
    api_call =  PillFillApiCall.new
    med_id = api_call.request_by_name(self.name)
    if api_call.request_by_id(med_id)
      self.label = api_call.request_by_id(med_id)
    end
  end
end

app/models/pill_fill_api_call.rb
require 'open-uri'
class PillFillApiCall
  def request_by_name(med_name)
   response = open("https://developer.pillfill.com:443/service/v1/products?term=#{med_name}&type=name&page=0",
    "api_key" => "7a9a6eec0bbbada9bb52ac3cff6e6a93")
   string = ""
   response.map do |line|
    string << line
   end
   med_id = JSON.parse(string)[0]["splId"]
   med_id
  end

  def request_by_id(id)
     response = open("https://developer.pillfill.com:443/service/v1/products/#{id}",
    "api_key" => "7a9a6eec0bbbada9bb52ac3cff6e6a93")
   string = ""
   response.map do |line|
    string << line
   end
   info = JSON.parse(string)[0]["splEntry"]["patientInformation"]["section"][2]["html"] #information for patients
   info
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_medications
  has_many :medications, through: :post_medications

  belongs_to :author, class_name: "User"
end

app/models/post_medication.rb
class PostMedication < ActiveRecord::Base
  belongs_to :post
  belongs_to :medication
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save :add_sample

  has_many :user_medications
  has_many :medications, through: :user_medications
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :commenter_id
  has_many :user_pharmacies
  has_many :pharmacies, through: :user_pharmacies

  def add_sample
    self.user_medications.new(medication: Medication.find_by(name: "Sample"), color: "red")
  end
end

app/models/user_medication.rb
class UserMedication < ActiveRecord::Base
  belongs_to :user
  belongs_to :medication
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :require_signin, except: [:index]
  def index
      respond_to do |format|
        format.html { render :index }
        format.json { render json: current_user}
      end
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def require_signin
    unless current_user
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path # halts request cycle
    end
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :require_signin

  def index
      user = current_user
      user.add_sample if !user.user_medications
      @ums = UserMedication.includes(:medication).where(user: user)
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @ums, methods: [:medication, :user]}
      end
  end

  def create
    @medication = Medication.create(name: medication_params[:name], dosage: medication_params[:dosage])
    @user_medication = UserMedication.create(user_med_params)
    if @user_medication.day == ""
       @user_medication.update_attributes(day: nil)
    end
    @ums = UserMedication.includes(:medication).where(user: current_user).last
    render json: @ums, methods: [:medication, :user]
  end

  def update
    UserMedication.find(params[:id]).update(day: params[:day])
    @ums = UserMedication.includes(:medication).where(user: @user)
    render json: @ums, methods: :medication
  end

  def medication_params
    params.require(:medication).permit(:name, :dosage)
  end

  def user_med_params
    params.permit(:alias, :color, :day).merge(user: current_user, medication: @medication)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  def index
    @posts = Post.all
    respond_to do |format|
        format.html { render :index }
        format.json { render json: @posts, methods: [:comments, :tags, :user]}
      end
  end

  def create
    post = Post.create(title: post_params[:title], content: post_params[:content], author: current_user)
    medication = Medication.find_by(name: params[:post][:medications_string])
    post.medications << medication if medication
    @posts = Post.all
    respond_to do |format|
        format.html { render :index }
        format.json { render json: @posts, methods: [:comments, :medications, :author]}
      end
  end

  def post_params
    params.require(:post).permit(:title, :content, :medications_string)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create]
  skip_before_action :require_signin, only: [:new, :create]

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to profile_path
    else
      flash[:notice] = "Bad Username or Password"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/user_medications_controller.rb
class UserMedicationsController < ApplicationController
  def update
    p params
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create]
  skip_before_action :require_signin, only: [:create]

  def create
    user = User.create(user_params)
    session[:user_id] = user.id
    redirect_to profile_path
  end

  def show
    # api_call = PillFillApiCall.new
    # @response = api_call.request
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_medications_helper.rb
module UserMedicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
   def format(field)
     (field + " " + content_tag(:small, 'Required')).html_safe
   end

end

app/views/application/index.html.erb
  <div id="left" class="small-3 columns left">
    <p class="bold">Your Meds.<p>
    <p class="bold">Your Online Resource.</p>
    <%= link_to "Get Started", "#", class: "orange_gradient button", id: "get_started", "data-reveal-id" => "signInModal" %>
    <div id="summary">
      My Pill Pal is your medical resource for community, scheduling and information all in one place!
    </div>
  </div>
  <div id="right" class="small-3 columns right">
    <p class="bold">Less Hassle.<p>
    <p class="bold">More of What Matters.</p>
    <div id="demo-buttons">
      <button class="orange_gradient">Watch Demo</button>
    </div>
  </div>
  <div id="carousel">
    <ul data-orbit>
      <li>
        <%= image_tag "elderly-women.jpg" %>
      </li>
      <li>
       <%= image_tag "elderly-happy.jpg" %>
      </li>
      <li>
        <%= image_tag "grandkids.jpg" %>
      </li>
    </ul>
  </div>

app/views/layouts/_nav_bar.html.erb
<div class="icon-bar five-up icon-text">
  <%= link_to root_path, class: "item" do %>
      <%= label_tag :home, "My Pill Pal", class: "nav-text" %>
  <% end %>
  <%= link_to forum_path, class: "item" do %>
    <%= image_tag "fi-comments.svg"%>
    <%= label_tag "Forum" %>
  <% end %>
  <%= link_to root_path, class: "item" do %>
    <%= image_tag "fi-video.svg"%>
    <%= label_tag "Demo" %>
 <% end %>
  <% if !current_user %>
    <%= link_to root_path, class: "item" do %>
       <%= image_tag "fi-torso.svg"%>
       <%= label_tag "Profile" %>
    <% end %>
  <% else %>
    <%= link_to profile_path, class: "item" do %>
         <%= image_tag "fi-torso.svg"%>
         <%= label_tag "Profile" %>
    <% end %>
  <% end %>
  <% if !current_user %>
    <a class="item" href="#" data-reveal-id="signInModal" id="modal">
      <%= image_tag "fi-compass.svg" %>
      <%= label_tag :signin, "Sign In" %>
      <%= render 'layouts/signin_modal' %>
    </a>
    <% else %>
      <%= link_to signout_path, class: "item" do %>
       <%= image_tag "fi-eject.svg"%>
       <%= label_tag :signout, "Sign Out" %>
      <% end %>
    <% end %>
</div>

app/views/layouts/_signin_modal.html.erb
<div id="signInModal" class="reveal-modal small" data-reveal aria-labelledby="modalSignIn" aria-hidden="true" role="dialog">
  <ul class="tabs" data-tab>
    <li class="tab-title active"><a href="#signin">Sign In</a></li>
    <li class="tab-title"><a href="#signup">Sign Up</a></li>
  </ul>
  <div class="tabs-content">
    <div class="content active" id="signin">
      <p>
      <%= render 'sessions/new' %>
    </p>
    </div>
    <div class="content" id="signup">
      <p>
       <%= render 'users/new' %>
     </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "My Pill Pal" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Oleo+Script" %>
    <%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Raleway:500" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="container">
      <div id="content-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_new.html.erb
<%= form_for :user, url: signup_path, :html => {"data-abide" => ''} do |f| %>
    <div class="name-field">
      <%= f.label(:user) {format('Username')} %>
      <%= f.text_field :username, :html => {"required" => '', "pattern" => "alpha_numeric"} %>
      <small class="error">Name is required and must contain at least one letter.</small>
    </div>
    <div class="password-field">
      <%= f.label(:user) {format('Password')} %>
      <%= f.password_field :password, id: :password, :html => {"required" => '', "pattern" => "alpha_numeric"} %>
      <small class="error">Your password can only contain letters and numbers.</small>
    </div>
    <div class="password-confirmation-field">
      <%= f.label(:user) {format('Confirm Password')} %>
      <%= f.password_field :password, id: :password, :html => {"required" => '', "pattern" => "alpha_numeric", "data-equalto"=> "password"} %>
      <small class="error">The password did not match</small>
    </div>
    <%= f.submit 'Submit', class: 'button' %>
  <% end %>